import 'package:note_sharing_project/models/subject.dart';

final List<String> semesterList = [
  "1st",
  "2nd",
  "3rd",
  "4th",
  "5th",
  "6th",
  "7th",
  "8th"
];

final List<String> programList = [
  "BESE",
  "BECS",
  "BEIT",
  "BCOM",
  "Civil Engineering",
  "Electronic",
];

final List<String> subList = [
  "Math1",
  "C",
  "WT",
  "PST",
  "NM",
  "OODM",
];

final subjectList = [
  Subject(name: "Math I", semester: "1st", program: "BESE"),
  Subject(name: "C", semester: "1st", program: "BESE"),
  Subject(name: "PST", semester: "1st", program: "BESE"),
  Subject(name: "FIT", semester: "1st", program: "BESE"),
  Subject(name: "Physic", semester: "1st", program: "BESE"),
  Subject(name: "CT", semester: "1st", program: "BESE"),
  Subject(name: "Drawing", semester: "2nd", program: "BESE"),
  Subject(name: "Math II", semester: "2nd", program: "BESE"),
  Subject(name: "LC", semester: "2nd", program: "BESE"),
  Subject(name: "MFCS", semester: "2nd", program: "BESE"),
  Subject(name: "C++", semester: "2nd", program: "BESE"),
  Subject(name: "Wt", semester: "2nd", program: "BESE"),
  Subject(name: "Math I", semester: "3rd", program: "BESE"),
  Subject(name: "C", semester: "3rd", program: "BESE"),
  Subject(name: "PST", semester: "3rd", program: "BESE"),
  Subject(name: "FIT", semester: "3rd", program: "BESE"),
  Subject(name: "Physic", semester: "3rd", program: "BESE"),
  Subject(name: "CT", semester: "3rd", program: "BESE"),
  Subject(name: "Drawing", semester: "4th", program: "BESE"),
  Subject(name: "Math II", semester: "4th", program: "BESE"),
  Subject(name: "LC", semester: "4th", program: "BESE"),
  Subject(name: "MFCS", semester: "4th", program: "BESE"),
  Subject(name: "C++", semester: "4th", program: "BESE"),
  Subject(name: "Wt", semester: "4th", program: "BESE"),
  Subject(name: "Math I", semester: "1st", program: "BEIT"),
  Subject(name: "C", semester: "1st", program: "BEIT"),
  Subject(name: "PST", semester: "1st", program: "BEIT"),
  Subject(name: "FIT", semester: "1st", program: "BEIT"),
  Subject(name: "Physic", semester: "1st", program: "BEIT"),
  Subject(name: "CT", semester: "1st", program: "BEIT"),
  Subject(name: "Drawing", semester: "2nd", program: "BEIT"),
  Subject(name: "Math II", semester: "2nd", program: "BEIT"),
  Subject(name: "LC", semester: "2nd", program: "BEIT"),
  Subject(name: "MFCS", semester: "2nd", program: "BEIT"),
  Subject(name: "C++", semester: "2nd", program: "BEIT"),
  Subject(name: "Wt", semester: "2nd", program: "BEIT"),
  Subject(name: "Math I", semester: "3rd", program: "BEIT"),
  Subject(name: "C", semester: "3rd", program: "BEIT"),
  Subject(name: "PST", semester: "3rd", program: "BEIT"),
  Subject(name: "FIT", semester: "3rd", program: "BEIT"),
  Subject(name: "Physic", semester: "3rd", program: "BEIT"),
  Subject(name: "CT", semester: "3rd", program: "BEIT"),
  Subject(name: "Drawing", semester: "4th", program: "BEIT"),
  Subject(name: "Math II", semester: "4th", program: "BEIT"),
  Subject(name: "LC", semester: "4th", program: "BEIT"),
  Subject(name: "MFCS", semester: "4th", program: "BEIT"),
  Subject(name: "C++", semester: "4th", program: "BEIT"),
  Subject(name: "Wt", semester: "4th", program: "BEIT"),
];
