import 'package:note_sharing_project/models/subject.dart';

final subjectList = [
  Subject(name: "Math I", semester: "1st", program: "BESE"),
  Subject(name: "C", semester: "1st", program: "BESE"),
  Subject(name: "PST", semester: "1st", program: "BESE"),
  Subject(name: "FIT", semester: "1st", program: "BESE"),
  Subject(name: "Physic", semester: "1st", program: "BESE"),
  Subject(name: "CT", semester: "1st", program: "BESE"),
  Subject(name: "Drawing", semester: "2nd", program: "BESE"),
  Subject(name: "Math II", semester: "2nd", program: "BESE"),
  Subject(name: "LC", semester: "2nd", program: "BESE"),
  Subject(name: "MFCS", semester: "2nd", program: "BESE"),
  Subject(name: "C++", semester: "2nd", program: "BESE"),
  Subject(name: "Wt", semester: "2nd", program: "BESE"),
  Subject(name: "DSA", semester: "3rd", program: "BESE"),
  Subject(name: "Math III", semester: "3rd", program: "BESE"),
  Subject(name: "MALP", semester: "3rd", program: "BESE"),
  Subject(name: "PQT", semester: "3rd", program: "BESE"),
  Subject(name: "JAVA", semester: "3rd", program: "BESE"),
  Subject(name: "SEF", semester: "3rd", program: "BESE"),
  Subject(name: "CG", semester: "4th", program: "BESE"),
  Subject(name: "COA", semester: "4th", program: "BESE"),
  Subject(name: "DBMS", semester: "4th", program: "BESE"),
  Subject(name: "NM", semester: "4th", program: "BESE"),
  Subject(name: "OODM", semester: "4th", program: "BESE"),
  Subject(name: "Project I", semester: "4th", program: "BESE"),
  Subject(name: "ADA", semester: "5th", program: "BESE"),
  Subject(name: "AOS", semester: "5th", program: "BESE"),
  Subject(name: "AI", semester: "5th", program: "BESE"),
  Subject(name: "ONM", semester: "5th", program: "BESE"),
  Subject(name: "SNM", semester: "5th", program: "BESE"),
  Subject(name: "SP", semester: "5th", program: "BESE"),
  Subject(name: "CN", semester: "6th", program: "BESE"),
  Subject(name: "EE", semester: "6th", program: "BESE"),
  Subject(name: "OOSD", semester: "6th", program: "BESE"),
  Subject(name: "MS", semester: "6th", program: "BESE"),
  Subject(name: "POPL", semester: "6th", program: "BESE"),
  Subject(name: "Project II", semester: "6th", program: "BESE"),
  Subject(name: "DS", semester: "7th", program: "BESE"),
  Subject(name: "Elective I", semester: "7th", program: "BESE"),
  Subject(name: "EAD", semester: "7th", program: "BESE"),
  Subject(name: "IPPR", semester: "7th", program: "BESE"),
  Subject(name: "RTS", semester: "7th", program: "BESE"),
  Subject(name: "STV", semester: "7th", program: "BESE"),
  Subject(name: "SPM", semester: "8th", program: "BESE"),
  Subject(name: "NP", semester: "8th", program: "BESE"),
  Subject(name: "Project III", semester: "8th", program: "BESE"),
  Subject(name: "Elective II", semester: "8th", program: "BESE"),
  Subject(name: "Math I", semester: "1st", program: "BEIT"),
  Subject(name: "C", semester: "1st", program: "BEIT"),
  Subject(name: "PST", semester: "1st", program: "BEIT"),
  Subject(name: "FIT", semester: "1st", program: "BEIT"),
  Subject(name: "Physic", semester: "1st", program: "BEIT"),
  Subject(name: "CT", semester: "1st", program: "BEIT"),
  Subject(name: "Drawing", semester: "2nd", program: "BEIT"),
  Subject(name: "Math II", semester: "2nd", program: "BEIT"),
  Subject(name: "LC", semester: "2nd", program: "BEIT"),
  Subject(name: "MFCS", semester: "2nd", program: "BEIT"),
  Subject(name: "C++", semester: "2nd", program: "BEIT"),
  Subject(name: "Wt", semester: "2nd", program: "BEIT"),
  Subject(name: "DSA", semester: "3rd", program: "BEIT"),
  Subject(name: "Math III", semester: "3rd", program: "BEIT"),
  Subject(name: "MALP", semester: "3rd", program: "BEIT"),
  Subject(name: "PQT", semester: "3rd", program: "BEIT"),
  Subject(name: "JAVA", semester: "3rd", program: "BEIT"),
  Subject(name: "SEF", semester: "3rd", program: "BEIT"),
  Subject(name: "CG", semester: "4th", program: "BEIT"),
  Subject(name: "COA", semester: "4th", program: "BEIT"),
  Subject(name: "DBMS", semester: "4th", program: "BEIT"),
  Subject(name: "NM", semester: "4th", program: "BEIT"),
  Subject(name: "OODM", semester: "4th", program: "BEIT"),
  Subject(name: "Project I", semester: "4th", program: "BEIT"),
  Subject(name: "ADA", semester: "5th", program: "BEIT"),
  Subject(name: "AOS", semester: "5th", program: "BEIT"),
  Subject(name: "AI", semester: "5th", program: "BEIT"),
  Subject(name: "ONM", semester: "5th", program: "BEIT"),
  Subject(name: "SNM", semester: "5th", program: "BEIT"),
  Subject(name: "SP", semester: "5th", program: "BEIT"),
  Subject(name: "CN", semester: "6th", program: "BEIT"),
  Subject(name: "EE", semester: "6th", program: "BEIT"),
  Subject(name: "OOSD", semester: "6th", program: "BEIT"),
  Subject(name: "MS", semester: "6th", program: "BEIT"),
  Subject(name: "POPL", semester: "6th", program: "BEIT"),
  Subject(name: "Project II", semester: "6th", program: "BEIT"),
  Subject(name: "DS", semester: "7th", program: "BEIT"),
  Subject(name: "Elective I", semester: "7th", program: "BEIT"),
  Subject(name: "EAD", semester: "7th", program: "BEIT"),
  Subject(name: "IPPR", semester: "7th", program: "BEIT"),
  Subject(name: "RTS", semester: "7th", program: "BEIT"),
  Subject(name: "STV", semester: "7th", program: "BEIT"),
  Subject(name: "SPM", semester: "8th", program: "BEIT"),
  Subject(name: "NP", semester: "8th", program: "BEIT"),
  Subject(name: "Project III", semester: "8th", program: "BEIT"),
  Subject(name: "Elective II", semester: "8th", program: "BEIT"),
  Subject(name: "Math I", semester: "1st", program: "BECS"),
  Subject(name: "C", semester: "1st", program: "BECS"),
  Subject(name: "PST", semester: "1st", program: "BECS"),
  Subject(name: "FIT", semester: "1st", program: "BECS"),
  Subject(name: "Physic", semester: "1st", program: "BECS"),
  Subject(name: "CT", semester: "1st", program: "BECS"),
  Subject(name: "Drawing", semester: "2nd", program: "BECS"),
  Subject(name: "Math II", semester: "2nd", program: "BECS"),
  Subject(name: "LC", semester: "2nd", program: "BECS"),
  Subject(name: "MFCS", semester: "2nd", program: "BECS"),
  Subject(name: "C++", semester: "2nd", program: "BECS"),
  Subject(name: "Wt", semester: "2nd", program: "BECS"),
  Subject(name: "DSA", semester: "3rd", program: "BECS"),
  Subject(name: "Math III", semester: "3rd", program: "BECS"),
  Subject(name: "MALP", semester: "3rd", program: "BECS"),
  Subject(name: "PQT", semester: "3rd", program: "BECS"),
  Subject(name: "JAVA", semester: "3rd", program: "BECS"),
  Subject(name: "SEF", semester: "3rd", program: "BECS"),
  Subject(name: "CG", semester: "4th", program: "BECS"),
  Subject(name: "COA", semester: "4th", program: "BECS"),
  Subject(name: "DBMS", semester: "4th", program: "BECS"),
  Subject(name: "NM", semester: "4th", program: "BECS"),
  Subject(name: "OODM", semester: "4th", program: "BECS"),
  Subject(name: "Project I", semester: "4th", program: "BECS"),
  Subject(name: "ADA", semester: "5th", program: "BECS"),
  Subject(name: "AOS", semester: "5th", program: "BECS"),
  Subject(name: "AI", semester: "5th", program: "BECS"),
  Subject(name: "ONM", semester: "5th", program: "BECS"),
  Subject(name: "SNM", semester: "5th", program: "BECS"),
  Subject(name: "SP", semester: "5th", program: "BECS"),
  Subject(name: "CN", semester: "6th", program: "BECS"),
  Subject(name: "EE", semester: "6th", program: "BECS"),
  Subject(name: "OOSD", semester: "6th", program: "BECS"),
  Subject(name: "MS", semester: "6th", program: "BECS"),
  Subject(name: "POPL", semester: "6th", program: "BECS"),
  Subject(name: "Project II", semester: "6th", program: "BECS"),
  Subject(name: "DS", semester: "7th", program: "BECS"),
  Subject(name: "Elective I", semester: "7th", program: "BECS"),
  Subject(name: "EAD", semester: "7th", program: "BECS"),
  Subject(name: "IPPR", semester: "7th", program: "BECS"),
  Subject(name: "RTS", semester: "7th", program: "BECS"),
  Subject(name: "STV", semester: "7th", program: "BECS"),
  Subject(name: "SPM", semester: "8th", program: "BECS"),
  Subject(name: "NP", semester: "8th", program: "BECS"),
  Subject(name: "Project III", semester: "8th", program: "BECS"),
  Subject(name: "Elective II", semester: "8th", program: "BECS"),
];
